# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_Add_VOResource_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='voresource_capability',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='voresource_interface',
            name='type',
            field=models.CharField(default='vr:WebBrowser', max_length=256),
        ),
        migrations.AlterField(
            model_name='voresource_accessurl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voresource_capability',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voresource_capability',
            name='standardID',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='voresource_interface',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
