# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_AdjustVOResource_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voresource_capability',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voresource_interface',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
