# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_Alter_ID_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voresource_interface',
            name='role',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='voresource_interface',
            name='version',
            field=models.CharField(blank=True, default='1.0', max_length=256, null=True),
        ),
    ]
