# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, null=True)),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('annotation', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(max_length=128, null=True)),
                ('location', models.CharField(max_length=128, null=True)),
                ('access', models.CharField(max_length=128, null=True)),
                ('size', models.CharField(max_length=128, null=True)),
                ('format', models.CharField(max_length=128, null=True)),
                ('annotation', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=1024, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_w3c.Activity')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_w3c.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='WasGeneratedBy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=1024, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_w3c.Activity')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_w3c.Entity')),
            ],
        ),
    ]
