# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_w3c', '0003_auto_20161004_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='affiliation',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
