# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('voprov:Project', 'voprov:Project'), ('prov:Person', 'prov:Person')], max_length=128, null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasAssociatedWith',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Activity')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='WasAttributedTo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Agent')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Entity')),
            ],
        ),
    ]
