# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0005_auto_20161201_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterDescription',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128, null=True)),
                ('datatype', models.CharField(max_length=128, null=True)),
                ('unit', models.CharField(max_length=128, null=True)),
                ('ucd', models.CharField(max_length=128, null=True)),
                ('utype', models.CharField(max_length=128, null=True)),
                ('arraysize', models.CharField(max_length=128, null=True)),
                ('annotation', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='parametervalues',
        ),
        migrations.RemoveField(
            model_name='activitydescription',
            name='parametertypes',
        ),
        migrations.AddField(
            model_name='parameterdescription',
            name='activitydescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.ActivityDescription'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Activity'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.ParameterDescription'),
        ),
    ]
