# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0006_auto_20161206_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
