# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0007_auto_20161206_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFlow',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prov_vo.Activity')),
            ],
            bases=('prov_vo.activity',),
        ),
        migrations.CreateModel(
            name='HadStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Activity')),
                ('activityflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityflow', to='prov_vo.ActivityFlow')),
            ],
        ),
        migrations.CreateModel(
            name='WasDerivedFrom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Entity')),
                ('progenitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progenitor', to='prov_vo.Entity')),
            ],
        ),
    ]
