# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-16 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0008_activityflow_hadstep_wasderivedfrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='description',
            new_name='description_link',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='docuLink',
            new_name='docu_link',
        ),
        migrations.RenameField(
            model_name='activitydescription',
            old_name='description',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='activitydescription',
            old_name='docuLink',
            new_name='docu_link',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='description',
            new_name='description_link',
        ),
        migrations.RenameField(
            model_name='entitydescription',
            old_name='description',
            new_name='annotation',
        ),
        migrations.RenameField(
            model_name='entitydescription',
            old_name='docuLink',
            new_name='docu_link',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='description',
            new_name='description_link',
        ),
        migrations.RenameField(
            model_name='used',
            old_name='description',
            new_name='description_link',
        ),
        migrations.RenameField(
            model_name='wasgeneratedby',
            old_name='description',
            new_name='description_link',
        ),
    ]
