# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-19 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0009_auto_20161216_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='description_link',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='docu_link',
            new_name='doculink',
        ),
        migrations.RenameField(
            model_name='activitydescription',
            old_name='docu_link',
            new_name='doculink',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='description_link',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='entitydescription',
            old_name='docu_link',
            new_name='doculink',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='description_link',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='used',
            old_name='description_link',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='wasgeneratedby',
            old_name='description_link',
            new_name='description',
        ),
    ]
