# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0010_auto_20161219_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_vo.ActivityDescription'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_vo.EntityDescription'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_vo.Activity'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_vo.ParameterDescription'),
        ),
        migrations.AlterField(
            model_name='parameterdescription',
            name='activitydescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_vo.ActivityDescription'),
        ),
        migrations.AlterField(
            model_name='used',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_vo.UsedDescription'),
        ),
        migrations.AlterField(
            model_name='wasgeneratedby',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_vo.WasGeneratedByDescription'),
        ),
    ]
