# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0012_change_datetime_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydescription',
            name='subtype',
            field=models.CharField(blank=True, choices=[('cs:halofinder', 'cs:halofinder'), ('cs:mergertreebuilding', 'cs:mergertreebuilding'), ('cs:galaxybuilding', 'cs:galaxybuilding')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='activitydescription',
            name='type',
            field=models.CharField(choices=[('cs:simulation', 'cs:simulation'), ('cs:post-processing', 'cs:postprocessing')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.CharField(choices=[('prov:Person', 'prov:Person'), ('prov:Organization', 'prov:Organization')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='wasassociatedwith',
            name='role',
            field=models.CharField(blank=True, choices=[('publisher', 'publisher'), ('creator', 'creator'), ('publisher', 'operator')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='wasattributedto',
            name='role',
            field=models.CharField(blank=True, choices=[('publisher', 'publisher'), ('creator', 'creator'), ('publisher', 'operator')], max_length=128, null=True),
        ),
    ]
