# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0013_adjust_roles_and_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdescription',
            name='default',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='parameterdescription',
            name='maxval',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='parameterdescription',
            name='minval',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
