# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0014_Add_minval_maxval_default_to_ParameterDescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='affiliation',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
