# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0015_allow_blank_for_agent_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='annotation',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='webpage',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
