# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0016_add_agent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='annotation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
