# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0017_parameter_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='agents',
            field=models.ManyToManyField(through='prov_vo.WasAssociatedWith', to='prov_vo.Agent'),
        ),
        migrations.AddField(
            model_name='entity',
            name='agents',
            field=models.ManyToManyField(through='prov_vo.WasAttributedTo', to='prov_vo.Agent'),
        ),
        migrations.AlterField(
            model_name='wasassociatedwith',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Activity'),
        ),
        migrations.AlterField(
            model_name='wasassociatedwith',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Agent'),
        ),
        migrations.AlterField(
            model_name='wasattributedto',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Agent'),
        ),
        migrations.AlterField(
            model_name='wasattributedto',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Entity'),
        ),
    ]
