# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0018_add_many-to-many_for_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='agents',
        ),
        migrations.AlterField(
            model_name='activity',
            name='agents',
            field=models.ManyToManyField(related_name='agents', through='prov_vo.WasAssociatedWith', to='prov_vo.Agent'),
        ),
    ]
