# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0019_auto_20170407_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='agents',
            field=models.ManyToManyField(through='prov_vo.WasAttributedTo', to='prov_vo.Agent'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='agents',
            field=models.ManyToManyField(through='prov_vo.WasAssociatedWith', to='prov_vo.Agent'),
        ),
    ]
