# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0020_auto_20170407_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='usedEntities',
            field=models.ManyToManyField(related_name='usedEntities', through='prov_vo.Used', to='prov_vo.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='generationActivities',
            field=models.ManyToManyField(related_name='generationActivities', through='prov_vo.WasGeneratedBy', to='prov_vo.Activity'),
        ),
    ]
