# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0021_auto_20170407_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='progenitors',
            field=models.ManyToManyField(related_name='wdprogenitors', through='prov_vo.WasDerivedFrom', to='prov_vo.Entity'),
        ),
    ]
