# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0022_entity_progenitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='agents',
            field=models.ManyToManyField(related_name='associatedActivities', through='prov_vo.WasAssociatedWith', to='prov_vo.Agent'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='usedEntities',
            field=models.ManyToManyField(related_name='usedForActivities', through='prov_vo.Used', to='prov_vo.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='agents',
            field=models.ManyToManyField(related_name='attributedEntities', through='prov_vo.WasAttributedTo', to='prov_vo.Agent'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='generationActivities',
            field=models.ManyToManyField(related_name='generatedEntities', through='prov_vo.WasGeneratedBy', to='prov_vo.Activity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='progenitors',
            field=models.ManyToManyField(related_name='derivatives', through='prov_vo.WasDerivedFrom', to='prov_vo.Entity'),
        ),
    ]
