# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0023_adjust_many-to_many-fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadstep',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Activity'),
        ),
        migrations.AlterField(
            model_name='hadstep',
            name='activityflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityflow', to='prov_vo.ActivityFlow'),
        ),
        migrations.AlterField(
            model_name='used',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Activity'),
        ),
        migrations.AlterField(
            model_name='used',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Entity'),
        ),
        migrations.AlterField(
            model_name='useddescription',
            name='activitydescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.ActivityDescription'),
        ),
        migrations.AlterField(
            model_name='useddescription',
            name='entitydescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.EntityDescription'),
        ),
        migrations.AlterField(
            model_name='wasderivedfrom',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Entity'),
        ),
        migrations.AlterField(
            model_name='wasderivedfrom',
            name='progenitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progenitor', to='prov_vo.Entity'),
        ),
        migrations.AlterField(
            model_name='wasgeneratedby',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Activity'),
        ),
        migrations.AlterField(
            model_name='wasgeneratedby',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Entity'),
        ),
        migrations.AlterField(
            model_name='wasgeneratedbydescription',
            name='activitydescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.ActivityDescription'),
        ),
        migrations.AlterField(
            model_name='wasgeneratedbydescription',
            name='entitydescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.EntityDescription'),
        ),
    ]
