# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('label', models.CharField(blank=True, max_length=1024, null=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedAlgorithm',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('algorithm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('executionTime', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputParameter',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterSetting',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('stringValue', models.CharField(blank=True, max_length=128, null=True)),
                ('numericValue', models.CharField(blank=True, max_length=128, null=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_simdm.InputParameter')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Protocol'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Protocol'),
        ),
    ]
