# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputparameter',
            old_name='label',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='parametersetting',
            old_name='numericValue',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='parametersetting',
            name='label',
        ),
        migrations.RemoveField(
            model_name='parametersetting',
            name='stringValue',
        ),
        migrations.AddField(
            model_name='inputparameter',
            name='datatype',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inputparameter',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='inputparameter',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Protocol'),
        ),
        migrations.AddField(
            model_name='parametersetting',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Experiment'),
        ),
        migrations.AddField(
            model_name='parametersetting',
            name='inputParameter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.InputParameter'),
        ),
    ]
