# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0002_auto_20170118_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
