# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0004_auto_20170118_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='code',
        ),
        migrations.AddField(
            model_name='appliedalgorithm',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Experiment'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='description',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='referenceURL',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
