# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0006_auto_20170119_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='executionTime',
            field=models.DateField(null=True),
        ),
    ]
