# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0008_add_data_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdataobjecttype',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='inputdataobjecttype',
            name='objecttype_ptr',
        ),
        migrations.RemoveField(
            model_name='inputdataobjecttype',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='outputdataobjecttype',
            name='objecttype_ptr',
        ),
        migrations.RemoveField(
            model_name='outputdataobjecttype',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='inputdataset',
            name='inputtype',
        ),
        migrations.RemoveField(
            model_name='outputdataset',
            name='objectType',
        ),
        migrations.DeleteModel(
            name='InputDataObjectType',
        ),
        migrations.DeleteModel(
            name='ObjectType',
        ),
        migrations.DeleteModel(
            name='OutputDataObjectType',
        ),
    ]
