# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0009_auto_20170206_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDataObjectType',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('label', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputDataObjectType',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('label', models.CharField(blank=True, max_length=1024, null=True)),
                ('protocol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Protocol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inputdataobjecttype',
            name='definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.OutputDataObjectType'),
        ),
        migrations.AddField(
            model_name='inputdataobjecttype',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Protocol'),
        ),
        migrations.AddField(
            model_name='inputdataset',
            name='inputtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.InputDataObjectType'),
        ),
        migrations.AddField(
            model_name='outputdataset',
            name='objectType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.OutputDataObjectType'),
        ),
    ]
