# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0010_Add object classes with meta class'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('outputDataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.OutputDataset')),
            ],
        ),
        migrations.CreateModel(
            name='InputDataObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataobject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.DataObject')),
                ('inputDataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.InputDataset')),
            ],
        ),
    ]
