# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0011_Add object classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=128, null=True)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Experiment')),
            ],
        ),
        migrations.RenameField(
            model_name='inputdataobject',
            old_name='dataobject',
            new_name='dataObject',
        ),
        migrations.AddField(
            model_name='party',
            name='affiliation',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Party'),
        ),
        migrations.AddField(
            model_name='contact',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Protocol'),
        ),
    ]
