# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0013_add_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='type',
            field=models.CharField(choices=[('Simulation', 'Simulation'), ('Analysis', 'Analysis')], max_length=128, null=True),
        ),
    ]
