# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0014_protocol_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputparameter',
            name='default',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inputparameter',
            name='maxval',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inputparameter',
            name='minval',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inputparameter',
            name='unit',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
