# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0015_Additional_fields_for_inputparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetting',
            name='annotation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
