# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_simdm', '0017_Change_annotation_char_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('datatype', models.CharField(blank=True, max_length=1024, null=True)),
                ('unit', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('dataObjectType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.OutputDataObjectType')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('dataObject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.DataObject')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prov_simdm.Property')),
            ],
        ),
        migrations.AlterField(
            model_name='inputparameter',
            name='unit',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
